# Generated by Django 5.1.5 on 2026-08-22 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_enable_rls'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='deactivated_on',
            field=models.DateField(blank=True, null=True),
        ),
    ]
