# Generated by Django 5.1.5 on 2026-08-22 07:28

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_enable_rls'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SalaryStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monthly_wage', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('working_days_per_week', models.PositiveSmallIntegerField(default=5)),
                ('break_time_hours', models.DecimalField(decimal_places=2, default=1, max_digits=4)),
                ('pf_employee_percent', models.DecimalField(decimal_places=2, default=12, max_digits=5)),
                ('pf_employer_percent', models.DecimalField(decimal_places=2, default=12, max_digits=5)),
                ('professional_tax', models.DecimalField(decimal_places=2, default=200, max_digits=8)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.company')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='salary', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SalaryComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('basic', 'Basic Salary'), ('hra', 'House Rent Allowance'), ('standard', 'Standard Allowance'), ('performance_bonus', 'Performance Bonus'), ('lta', 'Leave Travel Allowance'), ('fixed', 'Fixed Allowance')], max_length=32)),
                ('computation_type', models.CharField(choices=[('percent_of_wage', 'Percentage of wage'), ('percent_of_basic', 'Percentage of basic'), ('fixed_amount', 'Fixed amount'), ('remainder', 'Remainder of wage')], max_length=20)),
                ('value', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.company')),
                ('structure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='payroll.salarystructure')),
            ],
            options={
                'ordering': ['id'],
                'constraints': [models.UniqueConstraint(fields=('structure', 'code'), name='one_component_per_code_per_structure')],
            },
        ),
    ]
